### ISSUE TITLE
Add support for category combinations

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-eventcapture#105]
Events are currently pushed against the default category combination.

We would need to :
- [x] Download on pull the category combinations associated to a program as attributes if defined
- [x] Add a filter when selecting the OU & program if the program has a category combination different from the default one, so the user can select the category option combination
- [x] On push, include in the URL the category combination used for pushing
- [x] On event pull, add category combinations

**Comment by ifoche** [comment]
Probably SCMM app can help. We implemented there the support for cat combos

**Comment by ifoche** [comment]
Re-opening it as it looks like it's failing with following server:
https://extranet.who.int/dhis2-dev (same credentials used for connecting to who-dev at upc)

The server answers with
```
{
httpStatus: "Internal Server Error",
httpStatusCode: 500,
status: "ERROR",
message: "query did not return a unique result: 2"
}
```

to the query:
https://extranet.who.int/dhis2-dev/api/events?page=0&program=EwH68ZzyDRk&orgUnit=DVnpk4xiXGJ&pageSize=50&attributeCos=Y7fcspgsU43&attributeCc=JzvGfLYkX17&fields=%5B%3Aall%5D

**Comment by ifoche** [comment]
Little update. I've realized that the previous error was related to a program that we don't need now, so after removing permission of the user for that program I'm getting the following error:

```
2018-10-16 16:26:20.776 23401-23401/org.hisp.dhis.android.eventcapture_eyeseetea_dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.hisp.dhis.android.eventcapture_eyeseetea_dev, PID: 23401
    java.lang.SecurityException: Failed to find provider OrganisationUnitProgramRelationship for user 0; expected to find a valid ContentProvider for this authority
        at android.os.Parcel.readException(Parcel.java:2005)
        at android.os.Parcel.readException(Parcel.java:1951)
        at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:768)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1927)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1916)
        at com.raizlabs.android.dbflow.runtime.FlowContentObserver.registerForContentChanges(FlowContentObserver.java:188)
        at org.hisp.dhis.android.sdk.persistence.loaders.ModelChangeObserver.registerObserver(ModelChangeObserver.java:54)
        at org.hisp.dhis.android.sdk.persistence.loaders.DbLoader.registerObservers(DbLoader.java:72)
        at org.hisp.dhis.android.sdk.persistence.loaders.DbLoader.onStartLoading(DbLoader.java:127)
        at android.support.v4.content.Loader.startLoading(Loader.java:272)
        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.start(LoaderManager.java:270)
        at android.support.v4.app.LoaderManagerImpl.doStart(LoaderManager.java:770)
        at android.support.v4.app.Fragment.onStart(Fragment.java:1393)
        at android.support.v4.app.DialogFragment.onStart(DialogFragment.java:414)
        at android.support.v4.app.Fragment.performStart(Fragment.java:2210)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1337)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(FragmentManager.java:2323)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2136)
        at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1998)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:709)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
